### PR TITLE
Func extractor

### PR DESCRIPTION
**Pull request by palanik1**
Replace ParseTXLStruct/Func functions with reading output from annotator.

### CODE REVIEW

**Review by sdsen — COMMENTED** [review]
can you remove the parsetxlfunction* commented code ?

**Comment by palanik1** [comment]
> can you remove the parsetxlfunction* commented code ?

oops..Done..

**Comment by sdsen** [comment]
Also, update the README :-).
Rest lgtm.

**Comment by palanik1** [comment]
Done..

> Also, update the README :-). Rest lgtm.

Done..

**Comment by palanik1** [comment]
@sdsen PTAL..

**Comment by sdsen** [comment]
lgtm.

**Pull request merged**
